# Generated by Django 4.0.3 on 2022-03-02 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_frame', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceAccount',
        ),
    ]
