# Generated by Django 4.0.3 on 2022-03-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stream_frame', '0002_delete_serviceaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('token', models.JSONField(blank=True, null=True)),
                ('client_secret', models.JSONField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
