# Generated by Django 4.0.3 on 2022-03-02 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream_frame', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('channel_id', models.CharField(max_length=70)),
                ('creds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_frame.oauthcredentials')),
            ],
        ),
    ]
